name: template_video_editor
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  multi_split_view: ^2.2.0
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # Video processing
  video_player: ^2.8.1
  ffmpeg_kit_flutter: ^6.0.3
  
  # File handling
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  
  # Database & Backend
  supabase_flutter: ^2.0.2
  
  # State management
  provider: ^6.1.1
  
  # UI utilities
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true