name: template_video_editor
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  
  # Video & Media
  video_player: ^2.8.1
  ffmpeg_kit_flutter: ^6.0.3
  image_picker: ^1.0.4
  camera: ^0.11.2
  
  # UI & Utils
  path_provider: ^2.1.1
  image: ^4.1.3
  uuid: ^4.1.0
  
  # State Management
  provider: ^6.1.1
  
  # HTTP & JSON
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7